import type { Metadata } from 'next';
import '@/src/styles/globals.scss'; // 글로벌 스타일 적용
import { inter } from '@/public/fonts/font'; // 글로벌 폰트 적용

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
